services:
  dev-app:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ../../:/app
      - ../../node_modules:/app/node_modules
      - ../../dist:/app/dist
    command: sh -c "npm i --quiet --ignore-scripts && npm run start:dev"
    ports:
      - "8080:8080"
